### ISSUE TITLE
noVNC 打开中文名称或者带空格的名称的虚拟机失败

### ISSUE THREAD

**Issue by tolbkni** [zstackorg/zstack-dashboard#71]
跟踪了一下代码执行路径

```
LOCAL_IP: new handler Process
LOCAL_IP - - [27/Mar/2016 15:03:52] "GET /http://ZSTACK_IP:5000/static/templates/console/vnc_auto.html?host=ZSTACK_IP&port=39190&token=5e64d1f323784cbb94892d%2017d1b5920f HTTP/1.1" 101 -
LOCAL_IP - - [27/Mar/2016 15:03:52] LOCAL_IP: Plain non-SSL (ws://) WebSocket connection
LOCAL_IP - - [27/Mar/2016 15:03:52] LOCAL_IP: Version hybi-13, base64: 'False'
handler exception: not enough arguments for format string
exception
Traceback (most recent call last):
  File "websockify/websocket.py", line 880, in top_new_client
    client = self.do_handshake(startsock, address)
  File "websockify/websocket.py", line 815, in do_handshake
    self.RequestHandlerClass(retsock, address, self)
  File "websockify/websocket.py", line 112, in __init__
    SimpleHTTPRequestHandler.__init__(self, req, addr, server)
  File "/usr/lib64/python2.7/SocketServer.py", line 649, in __init__
    self.handle()
  File "websockify/websocket.py", line 542, in handle
    SimpleHTTPRequestHandler.handle(self)
  File "/usr/lib64/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/lib64/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "websockify/websocket.py", line 508, in do_GET
    if not self.handle_websocket():
  File "websockify/websocket.py", line 481, in handle_websocket
    self.log_message("%s: Path: '%s'" % (client_addr, self.path))
  File "/usr/lib64/python2.7/BaseHTTPServer.py", line 458, in log_message
    format%args))
TypeError: not enough arguments for format string
Reaing zombies, active child count is 0
Ignoring interrupted syscall
```

websockify 判断请求路径不是 `/` 时，会调用 `log_message()` 方法，而请求路径带中文或者空格是，整个路径字符串是这样的 `/http://ZSTACK_IP:5000/static/templates/console/vnc_auto.html?host=10.165.8.223&port=39190&token=5e64d1f323784cbb94892d17d1b5920f&title=%E4%B8%AD%E6%96%87%E5%90%8D` 或者这样 `/http://ZSTACK_IP:5000/static/templates/console/vnc_auto.html?host=ZSTACK_IP&port=39190&token=5e64d1f323784cbb94892d%2017d1b5920f`，注意第二个例子没有 title 参数，依然会出现该问题，是因为 `log_message()` 在格式化字符串时将 `%` 开头的当作了占位符。

**Comment by tolbkni** [comment]
Hi all, I submit a patch here (kanaka/websockify#231) to fix the issue.

**Comment by youyk** [comment]
I have verified this bug is fixed.
